### PR TITLE
Create LICENSE

### LINKED ISSUE #40: Please provide LICENSE
From License term:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

Without this file, redistribution of this library violates its License.

### PR DESCRIPTION
**Pull request by cebe**
According to [composer.json](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/composer.json#L4) it should be MIT.

fixes #40

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by sebastianbergmann** [comment]
Can you tag a new release, please? Thanks!

**Comment by mvriel** [comment]
@sebastianbergmann done!

**Comment by sebastianbergmann** [comment]
Thanks!

**Pull request merged**
