### PR TITLE
DocBlock: add removeTag() method

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by jaapio** [comment]
Please add a unittests for this method. 

We will accept this after a test is added.

**Comment by TomasVotruba** [comment]
Thanks for getting to this.

I've added simple test

**Comment by jaapio** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
Thank you for fast work

**Comment by TomasVotruba** [comment]
Would you mind if I add coding standard check? I had to check manually, what could be automated

**Pull request merged**
