### PR TITLE
Delete composer.lock

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Lock files are really only meant for apps where it matters to fix dependices. For apps, it is usual to setup composer.json to only allow versions that will not introduce new breaking changes. Moreover, your lock file is actually stopping the tests from running!

### CODE REVIEW

**Comment by jaapio** [comment]
I do agree with you that we should remove the composer.lock, but simply remove it is not enough. We should run our tests against multiple versions of the dependencies. Same would apply for phpstan and psalm. If you have time to update this pr that would be great. But I won't merge just a remove of the composer.lock file like this.

**Comment by GrahamCampbell** [comment]
> We should run our tests against multiple versions of the dependencies. 

You can do that with composer. `--prefer-lowest --prefer-stable`. Take for example Laravel's test suite.

**Comment by GrahamCampbell** [comment]
This PR pretty much works perfectly, apart from that we can't test on PHP 8 because the dependencies are not ready yet.

**Comment by jaapio** [comment]
I'm closing this PR, the wanted approach is described in #243. PR's for that are welcome.

**Pull request closed without merging**
