### PR TITLE
[4.x] Actually fixed the tests

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by mvriel** [comment]
Weird that only 7.1 fails now ..

**Comment by GrahamCampbell** [comment]
Oh, I see. Sec...

**Comment by GrahamCampbell** [comment]
Kinda odd we don't also have a normal run of PHP 7.1, or do prefer lowest on 7.0 (as well as normal run of 7.0). That can be handled in another PR, though.

**Comment by GrahamCampbell** [comment]
Also, the code style run seems totally messed up?

**Comment by mvriel** [comment]
I have merged this PR as it improves the situation; the problem seen here is an issue in the TypeResolver with multibyte character strings I think

**Comment by mvriel** [comment]
Yes, @jaapio and I have been working on getting the CI pipeline in a much better shape; but we are focusing on master's of our libraries at the moment

**Comment by GrahamCampbell** [comment]
Doesn't look like 5.x even does a prefer lowest run tbh. Maybe we should remove it on 4.x too?

**Comment by mvriel** [comment]
Sorry, what do you mean by lowest run? I am not sure I understand

**Comment by GrahamCampbell** [comment]
`--prefer-lowest`

**Comment by mvriel** [comment]
@GrahamCampbell try it; let's see what happens :)

**Comment by mvriel** [comment]
I am looking at the TypeResolver's multibyte handling atm

**Comment by GrahamCampbell** [comment]
👍

**Pull request merged**
