### PR TITLE
Bumps type-resolver to latest version

### PR DESCRIPTION
**Pull request by jaapio**

### CODE REVIEW

**Comment by garak** [comment]
One month passed... any news on this?

**Comment by jaapio** [comment]
Close because I pushed a new tag of the type-resolver. This becomes obsolete

**Comment by garak** [comment]
Great! What about releasing a new tag here, also?

**Comment by jaapio** [comment]
currently cleaning up open issues, will try to create a new tag soon

**Comment by jaapio** [comment]
@garak just released v3.2.0. 

Happy coding!

**Pull request closed without merging**
