### PR TITLE
[4.x] Fixed Travis

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by mvriel** [comment]
Thanks Graham, I was running into the same issue and was about to look into it when I saw this PR. This is a timesaver for me!

**Comment by mvriel** [comment]
Ah darn .. still not :(

https://travis-ci.org/phpDocumentor/ReflectionDocBlock/builds/630120910?utm_source=github_status&utm_medium=notification

**Comment by GrahamCampbell** [comment]
It's fixed in the sense that the tests are at least running now. ;)

**Comment by GrahamCampbell** [comment]
If the test suite depends on an older version of typeresolver, then we should specify it in the dev-dependencies.

**Pull request merged**
